### ISSUE TITLE
Anime won't download when i set the download location to SD card

### ISSUE THREAD

**Issue by dreigithub** [aniyomiorg/aniyomi#729]
### Steps to reproduce

When i set my download location to my internal storage the anime and manga was downloaded but when i set my download location to SD Card only the manga was downloaded and it can't download the animes i want to watch

### Expected behavior

I thought this issue would be fixed because this issue already exist back the previous 0.12.3.6 version of Aniyomi but this issue still exist in the current 0.12.3.7 version I'm using and it's really hard because i want to download my animes to my SD Card coz my internal storage is full lol

### Actual behavior

It says "unsupported download location" or something, unfortunately i didn't screenshot and copy the report issue but yea the point is it won't download on SD Card and i just want this small issue to be fixed asap

### Aniyomi version

0.12.3.7

### Android version

Android 10

### Device

Tecno LD7 Pova

### Other details

I would really appreciate if this report gets noticed and fixed, tysm aniyomi fam.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.jmir.xyz/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.7](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by redsriracha** [comment]
I feel this falls in a same problem, but in my situation is using a cifs instead of sd. Maybe anything that is external storage is a problem.

While I am able to select my shared cifs folder, the download location was not able to pick the correct path. Resulting into a invalid location.
![image](https://user-images.githubusercontent.com/9197265/236661408-df38f5d0-8d71-4331-b9af-93c5dbf7f54d.png)

The "Shared URI" is the correct path to my cifs folder.
![image](https://user-images.githubusercontent.com/9197265/236661437-f9887622-1bdb-4c3f-aac2-13036bb14604.png)

Hopefully this could help narrow down the search for this issue.

**Comment by Quickdesh** [comment]
This has been fixed/added in the preview

https://github.com/aniyomiorg/aniyomi-preview

Steps to shift to this build:- 
1. Create a backup from "Backup and Restore"
2. Download the preview apk and install it
3. Restore the backup you created before in the same tab "Backup and Restore"

**Comment by YoussefJarray** [comment]
This issue has not been completely fixed. and has resurfaced in the newest update. steps mentioned did not fix the issue.

**Comment by DentyTxR** [comment]
still an issue on stable version, but SD cards work fine on preview version
