### ISSUE TITLE
Extension list issue

### ISSUE THREAD

**Issue by Masrurkeepit** [aniyomiorg/aniyomi#888]
### Steps to reproduce

1. go to extension section 

### Expected behavior

1. all extensions should be showed 

### Actual behavior

1. failed to get extension

### Aniyomi version

aniyomi r4517

### Android version

12

### Device

Samsung m21

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/jmir1/aniyomi-extensions/issues/new/choose).
- [X] I have tried the [troubleshooting guide](https://aniyomi.org/help/guides/troubleshooting/).
- [X] I have updated the app to version **[0.12.3.8](https://github.com/jmir1/aniyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by itzswagking** [comment]
I am getting the same issue in the manga section hope they fix it soon

**Comment by Zeynex** [comment]
Same issue ... anime works for me but not manga ... it just refuses to load ...

**Comment by Mohammad-Afaque** [comment]
Having Same issue on device huawei LTS update.

**Comment by kpowers1028** [comment]
I too have an extension update failure.

**Comment by anujptl8** [comment]
Facing same issue after I updated to 0.12.3.10
Reverting back to 0.12.3.8, issue didn't reproduce.
Device Vivo Iqoo 7

**Comment by Masrurkeepit** [comment]
@anujtl8 your step doesn't work for me.

**Comment by anujptl8** [comment]
I installed tachiyomi. and updated the extensions from their. So problem with manga is solved. but anime extensions are not getting loaded still

**Comment by rv-exe** [comment]
I have updated the manga extensions on tachiyomi as well, but the list still does not load in aniyomi. Only anime extensions are loading now.

**Comment by Masrurkeepit** [comment]
every single manga extension vanished from aniyomi.

**Comment by JSPSolvent** [comment]
Apparently this issue is fixed in tachoyomi version 0.14.4 and mentioned in the changelog under “bug fixes”. It seems to be an issue on devices that use the MIUI interface (Xiaomi, Huawei, Honor etc.). 

“Fix installing extensions on MIUI (@stevenyomi)” 

We need this bug fix applied to Aniyomi ASAP.

PS. Do not update the manga extensions if you’re planning to use aniyomi as they won’t be showing as sources anymore till this bug is resolved.

**Comment by stevenyomi** [comment]
Manga extensions are disappearing because Tachiyomi recently updated the extensions-lib version to 1.4, which Aniyomi doesn't support yet. (The extensions now have version 1.4.x)

@JSPSolvent The MIUI issue is totally another one. That issue is when people fail to install extensions (getting failed to parse package error) after downloading them.

**Comment by Samael006** [comment]
Until when is going to resolve this problem ?  I also can't download any
other manga extension, It doesn't showing at all

**Comment by Masrurkeepit** [comment]
Bro, if possible can you please fix the problem?@stevenyomi

**Comment by stevenyomi** [comment]
> Bro, if possible can you please fix the problem?

No, I'm not interested in this.

**Comment by Masrurkeepit** [comment]
I have updated all my current manga extension. therefore i can't find any in aniyomi. is there any way i can get them back? @stevenyomi

**Comment by stevenyomi** [comment]
> I have updated all my current manga extension. therefore i can't find any in aniyomi. is there any way i can get them back?

Find them in https://github.com/tachiyomiorg/tachiyomi-extensions/tree/5ff924127cbeff435efd1604fbb39ebfb67c3882/apk, then uninstall and reinstall the old version.

**Comment by Samfun75** [comment]
Use beta version at http://github.com/jmir1/aniyomi-mpv-beta/releases/latest

**Comment by Masrurkeepit** [comment]
thanks bro

**Comment by Masrurkeepit** [comment]
@Samfun75 bro can i use the latest updated extension in this version u  mentioned?

**Comment by Samfun75** [comment]
Yes, I have all my manga extensions on 1.4 and they work fine. Join the aniyomi discord if you need help.

**Comment by Samfun75** [comment]
👍

**Comment by Quickdesh** [comment]
Duplicate of #844
